layout:
  normalize:
    include: true
  type:
    include: true
  display:
    include: true
    spacing: true
    widths: true
    silent: true
    fractions: true
  flexbox:
    include: true
mediaquery:
  palm:
    include: true
    widths: true
    layout: true
    spacing: true
  lap:
    include: true
    widths: true
    layout: true
    spacing: true
  lap-and-up:
    include: true
    widths: true
    layout: true
    spacing: true
  portable:
    include: true
    widths: true
    layout: true
    spacing: true
  desk:
    include: true
    widths: true
    layout: true
    spacing: true
  desk-wide:
    include: false
    widths: true
    layout: true
    spacing: true
  under-desk-wide:
    include: true
    widths: true
    layout: true
    spacing: true
